# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d0766ec985ad3651ec7ca412a1bcb2752e5be0da3bc053cbc8ebdae47ec0e23d5d964fa7d32c5b8354bd5e43da9563f7b207db4675d87a8ab46d4588483dfc8

test:
  secret_key_base: 2d6789719a592588f4df1185055cd42a7dea14d0de7438aa8394e4d00ec6f581be9f014ae10ea458296befb2460cc5e14bd8cb90f1c44f15f2299021d39151b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
